package com.dts.vaclass.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dts.vaclass.database.bean.PayDataBean;
import com.dts.vaclass.database.bean.UserDataBean;
import com.dts.vaclass.database.dao.PayDataBeanDao;
import com.dts.vaclass.database.dao.UserDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig payDataBeanDaoConfig;
    private final DaoConfig userDataBeanDaoConfig;

    private final PayDataBeanDao payDataBeanDao;
    private final UserDataBeanDao userDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        payDataBeanDaoConfig = daoConfigMap.get(PayDataBeanDao.class).clone();
        payDataBeanDaoConfig.initIdentityScope(type);

        userDataBeanDaoConfig = daoConfigMap.get(UserDataBeanDao.class).clone();
        userDataBeanDaoConfig.initIdentityScope(type);

        payDataBeanDao = new PayDataBeanDao(payDataBeanDaoConfig, this);
        userDataBeanDao = new UserDataBeanDao(userDataBeanDaoConfig, this);

        registerDao(PayDataBean.class, payDataBeanDao);
        registerDao(UserDataBean.class, userDataBeanDao);
    }
    
    public void clear() {
        payDataBeanDaoConfig.clearIdentityScope();
        userDataBeanDaoConfig.clearIdentityScope();
    }

    public PayDataBeanDao getPayDataBeanDao() {
        return payDataBeanDao;
    }

    public UserDataBeanDao getUserDataBeanDao() {
        return userDataBeanDao;
    }

}
